### ISSUE TITLE
is_training in BatchNormalization

### ISSUE THREAD

**Issue by louislbc** [Apm5/tensorflow_2.0_tutorial#1]
Hi,

I found the batch normalization in CNN/ResNet_CIFAR.py did not call the is_training to differentiate the   training and test process. Is that correct? Thanks!

**Comment by Apm5** [comment]
@louislbc 
Thanks for your attention.
In [#139](https://github.com/Apm5/tensorflow_2.0_tutorial/blob/11670ef995e37c60c1861faba395e61653df16ee/CNN/ResNet_CIFAR.py#L139) and [#149](https://github.com/Apm5/tensorflow_2.0_tutorial/blob/11670ef995e37c60c1861faba395e61653df16ee/CNN/ResNet_CIFAR.py#L149), the `training` is different.

**Comment by louislbc** [comment]
Hi, I've solved the training problem of batch norm.  Thank you for your reply!

But I try to add some modification to the resnet in your framework, i.e., adding some perturbations after the Conv layer.  In the same code, after line 91
    delta = tf.Variable(lambda : tf.zeros_like(net))
    axis_1 = delta.shape[1]*delta.shape[2]*delta.shape[3]
    net = net + tf.norm(tf.reshape(net,(-1,axis_1)),axis=1)[:,None,None,None]*delta 

Then the error reports as follows
*** tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable _AnonymousVar103 from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/_AnonymousVar103/N10tensorflow3VarE does not exist. [Op:ReadVariableOp]
I have intialized the delta, in the first line. Is this error coming from the usage of Input in your code? Thanks!

**Comment by Apm5** [comment]
@louislbc 
I don't know how to solve the question in your code. But here is some my ideas.
If you want to add some perturbations, you can declare a new CLASS as [link](https://github.com/Apm5/tensorflow_2.0_tutorial/blob/11670ef995e37c60c1861faba395e61653df16ee/CNN/Layers.py#L7). In `call`, get the random delta and add it.

**Comment by louislbc** [comment]
I've solved the problem by rewriting it to the model class method. Thank you for your help and advice! May I have your email or wechat concact for future consultation? @Apm5
