### ISSUE TITLE
should word_num be len(word_index)+1?

### ISSUE THREAD

**Issue by CharlieZhuGJ** [Apm5/tensorflow_2.0_tutorial#2]
Hi:

Thank you for providing such a good material.

In this file [simple_example.py](https://github.com/Apm5/tensorflow_2.0_tutorial/blob/master/RNN/simple_example.py) 
the parameter word_num is 10000, while i run this code in my computer, an exception is raised:
InvalidArgumentError: indices[26,0] = 12089 is not in [0, 10000).

I think word_num should be set to len(word_index)+1, so i changed and tested again, and it worked.

I wonder if  the change is right? or is there something i forget?

Thank you.

**Comment by Apm5** [comment]
@CharlieZhuGJ 
Thank you for your attention.
Sorry, i do not repeat the error that you reported. What is `indices` ?
Do you change [this line](https://github.com/Apm5/tensorflow_2.0_tutorial/blob/04bcfc3e04eb3846549cd5bedd423d8af7468239/RNN/simple_example.py#L65) ?
Setting word_num to 10000 is just to ignore words with too few occurrences. `word_num = len(word_index)+1` is right too.

By the way, I realize that the data loaded in the code is only based on the local path. I add the download link for imdb data and GLoVe weight.

**Comment by CharlieZhuGJ** [comment]
@Apm5 
Thank you for your reply. Sorry, It is my fault. 

I used this line  to download data, which selects all the words defaultly, not the top 10000 words.
`(train_sequences, train_labels), (test_sequences, test_labels) = imdb.load_data()`

Thank you, and have a good day.
